### ISSUE TITLE
Limit Recording Time

### ISSUE THREAD

**Issue by ghost** [rharkanson/pyriscope#2]
When recording a live stream I just want to record 30mins then stop and convert, is it possible pyriscope can have strict recording time option.

**Comment by rharkanson** [comment]
Yes, very possible, and all thanks to ffmpeg! Since ffmpeg is at the heart of recording live streams and, as I just checked, has a `-t` argument, it's just a matter of capturing the `-t` argument in Pyriscope and passing it to ffmpeg when it is called to start recording....... which I have already done! It will be available in 1.2.5, which I will push soon.

The usage is: 

```
pyriscope <url> [-t <duration>]
```

where `duration` is defined by https://www.ffmpeg.org/ffmpeg-utils.html#time-duration-syntax.
