### ISSUE TITLE
Key Error using --agent option

### ISSUE THREAD

**Issue by ghost** [rharkanson/pyriscope#3]
I'm getting a keyerror while turning off User-agent, also without --agent option It hangs for a very longtime on "getting mocked user-agent". I'm on windows 7 32bit

```
PS C:\Users\linski> pyriscope https://www.periscope.tv/w/aP3dpzFEWUVYcHFyWnZFZ0x8MWRqR1hCbm1XYUx4Wq-_u2I8ZdgtxQ3mBHSZDtn7XoNM2geds9OqohnMB0_E --agent --convert
Downloading broadcast information.
Downloading live stream information.
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python34\Scripts\pyriscope.exe\__main__.py", line 9, in <module>
  File "C:\Python34\lib\site-packages\pyriscope\__main__.py", line 18, in main
    processor.process(args)
  File "C:\Python34\lib\site-packages\pyriscope\processor.py", line 325, in process
    live_url = FFMPEG_LIVE.format(url_parts['url'], req_headers['User-Agent'],  access_public['hls_url'], name)
KeyError: 'User-Agent'
```

**Comment by rharkanson** [comment]
Ah! Thank you for pointing this out. Leaving the `'User-Agent'` key in the `req_headers` dictionary is fine for the Python requests library as it just defaults to its own user agent. Turning off user agent mocking never fills out the `'User-Agent'` entry in the dictionary, hence the error. 

The reason for the hang experienced by leaving user agent mocking on is that the script tries to get a mocked user agent first from "http://api.useragent.io/"  and then from "http://labs.wis.nu/ua/" if the first fails. If they both fail, it should just load a constant string hardcoded in the app. Passing in the `-a` or `--agent` directive bypasses this altogether. I may change this in the next release, making user agent mocking OFF by default, and needing to pass in the directives to turn it ON.

Thank you for the bug report with the error printout. This should be fixed by the next release.
