### ISSUE TITLE
Recent Changes Broken Support

### ISSUE THREAD

**Issue by Micendria** [rharkanson/pyriscope#5]
Hi,

Thanks for the great tool.

Recent changes broken the tool, tough. Could you look into it?

Cheers

**Comment by chrisbog94** [comment]
Same issue as above

root@server:~# pyriscope https://www.periscope.tv/w/aUmpUTEwMTk2MTg2fDFZcUtETWFnZ01WR1Y5t7ivJzZy-XmU0WGjOJiZGbZFQV1-oG7ZyIGFVRdZcA==

Downloading broadcast information.

Error: Video expired/deleted/wasn't found: https://www.periscope.tv/w/aUmpUTEwMTk2MTg2fDFZcUtETWFnZ01WR1Y5t7ivJzZy-XmU0WGjOJiZGbZFQV1-oG7ZyIGFVRdZcA==

The video is definitely available, other tools are able to download it.

**Comment by Micendria** [comment]
@chrisbog94 , which other tools do you use please?

**Comment by rharkanson** [comment]
@Micendria The only changes made in the recent commit was only to prevent pre-Python-3 users from installing Pyriscope since it is only for Python 3+ as people were having issues since they installed it with their Python 2 pip. https://github.com/rharkanson/pyriscope/commit/79bfd74989c4c2a6a97a59d5b0f6fab3d3446de8

@chrisbog94 I, too, would like to know which other tools you use. Maybe there is another method I am unaware of to scrape the streams.
